#!/bin/bash
# Initialize Terraform Backend (S3 + DynamoDB)
# Creates remote state storage with locking

set -e

echo "🚀 Terraform Backend Initialization"
echo "===================================="

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
PROJECT_NAME="bme-agency"
AWS_REGION=${AWS_REGION:-us-east-1}
STATE_BUCKET="${PROJECT_NAME}-terraform-state"
LOCK_TABLE="${PROJECT_NAME}-terraform-lock"

echo -e "${BLUE}Project: $PROJECT_NAME${NC}"
echo -e "${BLUE}Region: $AWS_REGION${NC}"
echo ""

# Check AWS credentials
echo "🔍 Checking AWS credentials..."
if ! aws sts get-caller-identity &> /dev/null; then
    echo -e "${RED}❌ AWS credentials not configured${NC}"
    echo "Run ./setup-credentials.sh first"
    exit 1
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo -e "${GREEN}✓ AWS Account: $ACCOUNT_ID${NC}"

# Create S3 bucket for Terraform state
echo ""
echo "📦 Creating S3 bucket for Terraform state..."

if aws s3 ls "s3://$STATE_BUCKET" 2>/dev/null; then
    echo -e "${YELLOW}⚠️  Bucket already exists: $STATE_BUCKET${NC}"
else
    # Create bucket
    if [ "$AWS_REGION" == "us-east-1" ]; then
        aws s3api create-bucket \
            --bucket "$STATE_BUCKET" \
            --region "$AWS_REGION"
    else
        aws s3api create-bucket \
            --bucket "$STATE_BUCKET" \
            --region "$AWS_REGION" \
            --create-bucket-configuration LocationConstraint="$AWS_REGION"
    fi
    
    echo -e "${GREEN}✓ Bucket created: $STATE_BUCKET${NC}"
    
    # Enable versioning
    aws s3api put-bucket-versioning \
        --bucket "$STATE_BUCKET" \
        --versioning-configuration Status=Enabled
    
    echo -e "${GREEN}✓ Versioning enabled${NC}"
    
    # Enable encryption
    aws s3api put-bucket-encryption \
        --bucket "$STATE_BUCKET" \
        --server-side-encryption-configuration '{
            "Rules": [{
                "ApplyServerSideEncryptionByDefault": {
                    "SSEAlgorithm": "AES256"
                }
            }]
        }'
    
    echo -e "${GREEN}✓ Encryption enabled${NC}"
    
    # Block public access
    aws s3api put-public-access-block \
        --bucket "$STATE_BUCKET" \
        --public-access-block-configuration \
            "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
    
    echo -e "${GREEN}✓ Public access blocked${NC}"
    
    # Add lifecycle policy
    aws s3api put-bucket-lifecycle-configuration \
        --bucket "$STATE_BUCKET" \
        --lifecycle-configuration '{
            "Rules": [{
                "Id": "DeleteOldVersions",
                "Status": "Enabled",
                "NoncurrentVersionExpiration": {
                    "NoncurrentDays": 90
                }
            }]
        }'
    
    echo -e "${GREEN}✓ Lifecycle policy applied${NC}"
    
    # Add tags
    aws s3api put-bucket-tagging \
        --bucket "$STATE_BUCKET" \
        --tagging 'TagSet=[
            {Key=Project,Value=ModelAgencyPlatform},
            {Key=Purpose,Value=TerraformState},
            {Key=ManagedBy,Value=Terraform}
        ]'
    
    echo -e "${GREEN}✓ Tags applied${NC}"
fi

# Create DynamoDB table for state locking
echo ""
echo "🔒 Creating DynamoDB table for state locking..."

if aws dynamodb describe-table --table-name "$LOCK_TABLE" --region "$AWS_REGION" &>/dev/null; then
    echo -e "${YELLOW}⚠️  Table already exists: $LOCK_TABLE${NC}"
else
    aws dynamodb create-table \
        --table-name "$LOCK_TABLE" \
        --attribute-definitions AttributeName=LockID,AttributeType=S \
        --key-schema AttributeName=LockID,KeyType=HASH \
        --billing-mode PAY_PER_REQUEST \
        --region "$AWS_REGION" \
        --tags Key=Project,Value=ModelAgencyPlatform Key=Purpose,Value=StateLocking Key=ManagedBy,Value=Terraform
    
    echo -e "${GREEN}✓ Table created: $LOCK_TABLE${NC}"
    
    # Wait for table to be active
    echo "⏳ Waiting for table to be active..."
    aws dynamodb wait table-exists --table-name "$LOCK_TABLE" --region "$AWS_REGION"
    echo -e "${GREEN}✓ Table is active${NC}"
    
    # Enable point-in-time recovery
    aws dynamodb update-continuous-backups \
        --table-name "$LOCK_TABLE" \
        --point-in-time-recovery-specification PointInTimeRecoveryEnabled=true \
        --region "$AWS_REGION"
    
    echo -e "${GREEN}✓ Point-in-time recovery enabled${NC}"
fi

# Create backend configuration file
echo ""
echo "📝 Creating backend configuration..."

cat > ../backend-config.hcl << EOF
# Terraform Backend Configuration
# Auto-generated by initialize-backend.sh

bucket         = "$STATE_BUCKET"
key            = "modeling-agency/terraform.tfstate"
region         = "$AWS_REGION"
encrypt        = true
dynamodb_table = "$LOCK_TABLE"

# Additional settings
versioning = true
EOF

echo -e "${GREEN}✓ Backend config created: backend-config.hcl${NC}"

# Update main.tf with backend config
echo ""
echo "🔧 Updating main.tf with backend configuration..."

# Check if backend block exists in main.tf
if grep -q "backend \"s3\"" ../main.tf; then
    echo -e "${YELLOW}⚠️  Backend configuration already exists in main.tf${NC}"
else
    echo -e "${YELLOW}⚠️  Please manually add backend configuration to main.tf${NC}"
fi

# Initialize Terraform with backend
echo ""
echo "🎯 Initializing Terraform with remote backend..."
cd ..

# Run terraform init with backend config
terraform init -backend-config=backend-config.hcl -reconfigure

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Terraform initialized successfully${NC}"
else
    echo -e "${RED}❌ Terraform initialization failed${NC}"
    exit 1
fi

# Verify backend
echo ""
echo "✅ Verifying backend configuration..."
terraform state list 2>/dev/null || echo "No state yet (this is normal for new setup)"

# Create workspace for dev environment
echo ""
echo "🏗️  Creating Terraform workspaces..."

terraform workspace new dev 2>/dev/null || terraform workspace select dev
echo -e "${GREEN}✓ Dev workspace ready${NC}"

terraform workspace new staging 2>/dev/null || echo "Staging workspace exists"
terraform workspace new prod 2>/dev/null || echo "Prod workspace exists"

terraform workspace select dev
echo -e "${GREEN}✓ Using dev workspace${NC}"

# Display summary
echo ""
echo -e "${GREEN}✅ Backend initialization complete!${NC}"
echo ""
echo "📊 Backend Summary:"
echo "  State Bucket: s3://$STATE_BUCKET"
echo "  Lock Table: $LOCK_TABLE"
echo "  Region: $AWS_REGION"
echo "  Account: $ACCOUNT_ID"
echo ""
echo "🎯 Backend Features:"
echo "  ✓ Remote state storage"
echo "  ✓ State locking (DynamoDB)"
echo "  ✓ Versioning enabled"
echo "  ✓ Encryption at rest"
echo "  ✓ Public access blocked"
echo "  ✓ Lifecycle policies"
echo "  ✓ Point-in-time recovery"
echo ""
echo "Next steps:"
echo "1. Review terraform/backend-config.hcl"
echo "2. Run: ./deploy-dev.sh"
echo ""

cd scripts
