/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XXXXXXXXX", // Replace with your User Pool ID
    "aws_user_pools_web_client_id": "XXXXXXXXXXXXXXXXXXXXXXXXXX", // Replace with your App Client ID
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "GIVEN_NAME",
        "FAMILY_NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://XXXXXXXXXXXXXXXXXXXX.appsync-api.us-east-1.amazonaws.com/graphql", // Replace with your AppSync endpoint
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-XXXXXXXXXXXXXXXXXXXX", // Replace with your API key
    "aws_cloud_logic_custom": [
        {
            "name": "doohapi",
            "endpoint": "https://XXXXXXXXXX.execute-api.us-east-1.amazonaws.com/prod", // Replace with your API Gateway endpoint
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "bme-creative-assets-XXXXXXXXXX", // Replace with your S3 bucket name
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_cloudfront_domain": "XXXXXXXXXXXX.cloudfront.net", // Replace with your CloudFront domain
    "predictions": {
        "convert": {
            "translateText": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "sourceLanguage": "en",
                    "targetLanguage": "es"
                }
            }
        }
    },
    "analytics": {
        "plugins": {
            "awsKinesisProvider": {
                "kinesisConfig": {
                    "region": "us-east-1",
                    "bufferSize": 1000,
                    "flushSize": 100,
                    "flushInterval": 5000,
                    "resendLimit": 5
                }
            }
        }
    }
};

export default awsconfig;