"""
Remediation Lambda - Processes AWS Inspector findings via EventBridge
and creates GitHub issues for discovered vulnerabilities.

Triggered by EventBridge rule matching Inspector finding events.
Reads GitHub token from AWS Secrets Manager.
"""

import json
import logging
import os

import boto3
import requests

logger = logging.getLogger()
logger.setLevel(logging.INFO)

secrets_client = boto3.client("secretsmanager", region_name=os.environ.get("AWS_REGION", "us-east-1"))

GITHUB_SECRET_ARN = os.environ.get("GITHUB_SECRET_ARN", "")
GITHUB_REPO = os.environ.get("GITHUB_REPO", "")
DEFAULT_BRANCH = os.environ.get("DEFAULT_BRANCH", "main")
ENVIRONMENT = os.environ.get("ENVIRONMENT", "dev")

_github_token_cache: str | None = None


def _get_github_token() -> str:
    global _github_token_cache
    if _github_token_cache:
        return _github_token_cache
    resp = secrets_client.get_secret_value(SecretId=GITHUB_SECRET_ARN)
    secret = json.loads(resp["SecretString"])
    _github_token_cache = secret.get("token", secret.get("GITHUB_TOKEN", ""))
    return _github_token_cache


def _severity_label(severity: str) -> str:
    mapping = {
        "CRITICAL": "severity:critical",
        "HIGH": "severity:high",
        "MEDIUM": "severity:medium",
        "LOW": "severity:low",
        "INFORMATIONAL": "severity:info",
    }
    return mapping.get(severity.upper(), "severity:unknown")


def _build_issue_body(finding: dict) -> str:
    title = finding.get("title", "Unknown vulnerability")
    description = finding.get("description", "No description available.")
    severity = finding.get("severity", "UNKNOWN")
    resource_type = finding.get("type", "Unknown")
    first_observed = finding.get("firstObservedAt", "N/A")
    last_observed = finding.get("lastObservedAt", "N/A")
    inspector_score = finding.get("inspectorScore", "N/A")

    vuln_id = ""
    package_info = ""
    vuln_details = finding.get("packageVulnerabilityDetails", {})
    if vuln_details:
        vuln_id = vuln_details.get("vulnerabilityId", "")
        source_url = vuln_details.get("sourceUrl", "")
        vulnerable_packages = vuln_details.get("vulnerablePackages", [])
        if vulnerable_packages:
            pkg = vulnerable_packages[0]
            package_info = (
                f"- **Package**: {pkg.get('name', 'N/A')} {pkg.get('version', '')}\n"
                f"- **Fixed in**: {pkg.get('fixedInVersion', 'No fix available')}\n"
                f"- **Remediation**: {pkg.get('remediation', 'N/A')}\n"
            )

    resources = finding.get("resources", [])
    resource_lines = ""
    for r in resources:
        resource_lines += f"- `{r.get('type', 'Unknown')}`: {r.get('id', 'N/A')}\n"

    body = f"""## AWS Inspector Finding — {severity}

**{title}**

| Field | Value |
|-------|-------|
| Severity | {severity} |
| Inspector Score | {inspector_score} |
| Type | {resource_type} |
| First Observed | {first_observed} |
| Last Observed | {last_observed} |
| Environment | {ENVIRONMENT} |

### Description
{description}

"""
    if vuln_id:
        body += f"### Vulnerability\n- **CVE**: {vuln_id}\n- **Source**: {source_url}\n{package_info}\n"

    if resource_lines:
        body += f"### Affected Resources\n{resource_lines}\n"

    body += (
        "---\n"
        "*Auto-generated by CVE Remediation Lambda from AWS Inspector finding.*\n"
    )
    return body


def _create_github_issue(title: str, body: str, labels: list[str]) -> dict:
    token = _get_github_token()
    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    payload = {"title": title, "body": body, "labels": labels}
    resp = requests.post(url, headers=headers, json=payload, timeout=15)
    resp.raise_for_status()
    issue = resp.json()
    return {"issue_number": issue["number"], "html_url": issue["html_url"]}


def _put_metric(metric_name: str, value: float = 1.0):
    try:
        cw = boto3.client("cloudwatch", region_name=os.environ.get("AWS_REGION", "us-east-1"))
        cw.put_metric_data(
            Namespace="CVERemediation",
            MetricData=[
                {
                    "MetricName": metric_name,
                    "Value": value,
                    "Unit": "Count",
                    "Dimensions": [{"Name": "Environment", "Value": ENVIRONMENT}],
                }
            ],
        )
    except Exception as e:
        logger.warning("Failed to put CloudWatch metric %s: %s", metric_name, e)


def handler(event, context):
    """
    Lambda entry point. Expects EventBridge event with Inspector finding detail.
    """
    logger.info("Received event: %s", json.dumps(event, default=str)[:2000])

    _put_metric("CVE_Detected_Count")

    detail = event.get("detail", {})
    if not detail:
        logger.warning("No detail in event, skipping")
        return {"statusCode": 200, "body": "No detail found"}

    severity = detail.get("severity", "UNKNOWN")
    title_raw = detail.get("title", "AWS Inspector Finding")
    finding_type = detail.get("type", "")

    issue_title = f"[{ENVIRONMENT.upper()}] [{severity}] {title_raw}"
    labels = [
        _severity_label(severity),
        "aws-inspector",
        f"env:{ENVIRONMENT}",
        "auto-remediation",
    ]

    body = _build_issue_body(detail)

    try:
        result = _create_github_issue(issue_title, body, labels)
        _put_metric("Remediation_Issues_Created")
        logger.info("Created GitHub issue #%s: %s", result["issue_number"], result["html_url"])
        return {
            "statusCode": 201,
            "body": json.dumps(result),
        }
    except requests.exceptions.HTTPError as e:
        logger.error("GitHub API error: %s — %s", e.response.status_code, e.response.text)
        return {
            "statusCode": 502,
            "body": f"GitHub API error: {e.response.status_code}",
        }
    except Exception as e:
        logger.error("Unexpected error creating issue: %s", e)
        return {
            "statusCode": 500,
            "body": str(e),
        }
